name: Build

on:
  pull_request:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Install Rust
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable
          targets: x86_64-pc-windows-msvc

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: |
          cargo build --locked --profile=max-opt

      - name: Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          files: target/max-opt/asr-lso.exe
          name: Latest
          tag_name: latest
          body: This contains the latest version of the asr-lso bridge tool.

