name: Build

on:
  pull_request:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Install Rust
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable
          targets: x86_64-pc-windows-msvc

      - name: Build
        run: |
          cargo build --locked --profile=max-opt

      - name: Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          files: target/max-opt/asr-lso.exe
          name: Latest
          tag_name: latest
          body: This contains the latest version of the asr-lso bridge tool.

  clippy:
    name: Check clippy lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Install Rust
        uses: hecrj/setup-rust-action@v2
        with:
          components: clippy
          targets: x86_64-pc-windows-msvc

      - name: Run Clippy
        run: cargo clippy --all-features

  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Install Rust
        uses: hecrj/setup-rust-action@v2
        with:
          components: rustfmt
          targets: x86_64-pc-windows-msvc

      - name: Run cargo fmt
        run: cargo fmt -- --check || true
